### ISSUE TITLE
`urllib3` v2 breaks `binstar_client` package

### ISSUE THREAD

**Issue by peterbygrave** [conda-forge/anaconda-client-feedstock#40]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The `urllib3` package created v2 with breaking changes:

```
conda create -n anaconda-client-env anaconda-client
conda activate anaconda-client-env
python -c "import binstar_client"        
```

giving:
```               
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/peter/miniconda3/envs/anaconda-client-env/lib/python3.11/site-packages/binstar_client/__init__.py", line 26, in <module>
    from .requests_ext import NullAuth
  File "/Users/peter/miniconda3/envs/anaconda-client-env/lib/python3.11/site-packages/binstar_client/requests_ext.py", line 11, in <module>
    from urllib3.filepost import choose_boundary, iter_fields
ImportError: cannot import name 'iter_fields' from 'urllib3.filepost' (/Users/peter/miniconda3/envs/anaconda-client-env/lib/python3.11/site-packages/urllib3/filepost.py)
```

The following environment resolves and imports correctly:

```
conda create -n anaconda-client-env anaconda-client "urllib3<2"
```

Therefore I recommend pinning `urllib3 >=1.26.4,<2.0.0a` (or however is best to form an upper pin excluding pre-releases etc).

I first observed this https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/242.

Many thanks

### Installed packages

```shell
anaconda-client
```

### Environment info

```shell
active environment : anaconda-client-env
    active env location : /Users/peter/miniconda3/envs/anaconda-client-env
            shell level : 4
       user config file : /Users/peter/.condarc
 populated config files : /Users/peter/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.2.1=0
                          __unix=0=0
       base environment : /Users/peter/miniconda3  (writable)
      conda av data dir : /Users/peter/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/peter/miniconda3/pkgs
                          /Users/peter/.conda/pkgs
       envs directories : /Users/peter/miniconda3/envs
                          /Users/peter/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.10 Darwin/22.3.0 OSX/13.2.1 solver/libmamba conda-libmamba-solver/22.8.1 libmambapy/1.4.0
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by jakirkham** [comment]
Thanks for the report! 🙏

Would you be interested in submitting a PR to constrain this dependency?
